### ISSUE TITLE
Desktop libGDX: solved flickering problem by changing OpenGL settings

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#257] opened 2016-11-26 17:38 UTC
I had these problems when running GdxMapApp in the desktop

- Map and Labels are flickering just when moving the mouse. After debugging I found that this problem occured here: 
swapBuffers() in https://github.com/LWJGL/lwjgl/blob/lwjgl2.9.2/src/java/org/lwjgl/opengl/Display.java#L646
called from https://github.com/libgdx/libgdx/blob/1.9.4/backends/gdx-backend-lwjgl/src/com/badlogic/gdx/backends/lwjgl/LwjglApplication.java#L224
- Sometimes tiles are not displayed, depending on the tilt/rotation

These two problems were solved after setting **_Buffer-flipping mode_** to **_Use block transfer_**
![nvidia-set-buffer-flipping-mode](https://cloud.githubusercontent.com/assets/1283445/20642049/ca31259c-b405-11e6-8071-8e8ba01df757.png)

Tiles which are not displayed
![vtm-tiles-not-displayed-1](https://cloud.githubusercontent.com/assets/1283445/20642106/e0169a12-b406-11e6-8f9a-fedb0a6fd0a4.png)

![vtm-tiles-not-displayed-2](https://cloud.githubusercontent.com/assets/1283445/20642109/eb67d430-b406-11e6-9a5c-3383dd5eed23.png)

**Comment by devemux86** [comment] 2016-11-26 17:45
Related to #149?

Regarding missed tiles, OpenScienceMap tile server lately does not provide always all the requested tiles.
Are you sure you don't have missed tiles now?

**Comment by devemux86** [comment] 2016-11-26 17:57
Note that we can use also other libGDX backends.
I just chose LWJGL for its fine Java integration.

There are alternatives like [LWJGL3](https://www.lwjgl.org/), [JGLFW](https://github.com/badlogic/jglfw), [JOGL](http://jogamp.org/jogl/www/) which I tested in the past.

If there is interest, I could implement the GL translators and add them in separate modules for testing.

**Comment by wolfgang-ch** [comment] 2016-11-26 18:17
It's difficult to get the map at the same position but as you can see in the image, the tiles are now displayed correctly.

I also increased MAX_TILT https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/map/Viewport.java#L42, then it is possible that tiles are not displayed

![vtm-tiles-not-displayed-3](https://cloud.githubusercontent.com/assets/1283445/20642293/c943e1b4-b40b-11e6-9d67-c9cbb198e23b.png)

**Comment by wolfgang-ch** [comment] 2016-11-26 18:25
I would like to integrate the VTM map in an Eclipse RCP application but currently I'm not sure which could be the best GL framework.

I already integrated https://goworldwind.org/ in my RCP app https://github.com/wolfgang-ch/mytourbook which is using JOGL but this map seems to be currently in maintainance mode for the desktop

**Comment by devemux86** [comment] 2016-11-26 18:28
> this map seems to be currently in maintainance mode for the desktop

What do you mean?

**Comment by wolfgang-ch** [comment] 2016-11-26 18:34
WorldWindJava has not much changes compared to HTML/Android versions
https://github.com/NASAWorldWind

**Comment by wolfgang-ch** [comment] 2016-11-27 07:25
### GL translators
> There are alternatives like LWJGL3, JGLFW, JOGL which I tested in the past.
> 
> If there is interest, I could implement the GL translators and add them in separate modules.

I'm be interested in a LWJGL3 GL translator, would be cool you can implement it.

### swapBuffers Problem
Instead of setting _**Buffer-flipping mode**_ to _**Use block transfer**_ this problem may propably also be solved when both buffers have the same conent but with my current OpenGL skills I'm not able to fix this problem.

**Comment by devemux86** [comment] 2016-11-27 08:44
>I'm be interested in a LWJGL3 GL translator, would be cool you can implement it.

I created #258 for that.
We need better organization of `vtm-desktop` first as it's integrated with LWJGL.

**Comment by xamix** [comment] 2017-02-15 12:06
To complete on this issue:

Have the same exact problem, the FIX in Nvidia settings seem to work also for me.

Here is my current hardware and software (Windows 7 + Nvidia Quadro):

![setup](https://cloud.githubusercontent.com/assets/9742044/22973726/35daeb8a-f37f-11e6-87a2-63d92d25ad0c.JPG)

Please note that after this change, some tile seem to not display correctly:

![bug](https://cloud.githubusercontent.com/assets/9742044/22973807/8430fe82-f37f-11e6-86d8-08a7bff7d459.png)

Don't know if it's related but before this change all tile seem to display correctly.

**Comment by devemux86** [comment] 2017-09-21 17:53
Closing, please reopen if needed.

**Comment by wolfgang-ch** [comment] 2017-09-22 12:48
I updated vtm to the current version and it is still flickering when **Buffer-flipping mode** is not set to **Use block transfer**

This problem occures also by other users of my app 

> I run MT on a Dell Precision 7710 with a professional Nvidia Quadro M3000M GPU and often there is a flickering effect on the 2.5D map.

This was also solved by setting the buffer flipping mode

I attached a video which shows the flickering but I had to put it into a zip file, mp4 cannot be attached

[Video_2017-09-22_143124.zip](https://github.com/mapsforge/vtm/files/1324554/Video_2017-09-22_143124.zip)

**Comment by devemux86** [comment] 2017-09-22 13:50
- Do you see this behaviour also with `vtm-playground` samples?
(to separate from any app custom implementation)

- Have you tried changing the various parameters in used `LwjglApplicationConfiguration`, to see if something improves the situation?

**Comment by xamix** [comment] 2017-09-22 18:00
For information,
I also always have the same issue with your last Cruiser GL ".exe"


Le 22 sept. 2017 15:50, "Emux" <notifications@github.com> a écrit :


   -

   Do you see this behaviour also with vtm-playground samples?
   (to separate from any app custom implementation)
   -

   Have you tried changing the various parameters in used
   LwjglApplicationConfiguration, to see if something improves the
   situation?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mapsforge/vtm/issues/257#issuecomment-331452327>, or mute
the thread

**Comment by wolfgang-ch** [comment] 2017-09-23 05:14
I have the same issue with the vtm-gdx sample, see video

[Video_2017-09-23_065619.zip](https://github.com/mapsforge/vtm/files/1326294/Video_2017-09-23_065619.zip)

> Have you tried changing the various parameters in used LwjglApplicationConfiguration, to see if something improves the situation?

Not yet, which properties should I test?


I've not very much OpenGL skills but I discovered this problem in the swapBuffer method in https://github.com/LWJGL/lwjgl/blob/lwjgl2.9.2/src/java/org/lwjgl/opengl/Display.java#L646 as pointed out in my first comment and I'm wondering why the buffers are swapped only when moving the mouse and doing nothing else.

**Comment by wolfgang-ch** [comment] 2017-09-23 05:20
The solution which I found accidentally by setting **Buffer-flipping mode** to **Use block transfer** may propably solve only the symptoms and not the issue itself.

**Comment by devemux86** [comment] 2018-01-04 19:11
`GdxMap.render` has a check to skip renders. If we comment it, then works without flickering (no MSAA needed).
I pushed the changes in [libGDX](https://github.com/mapsforge/vtm/tree/libGDX) branch.
Tested on Android and Linux with rendering seems fine. More tests needed on Windows and macOS.
Can you also test in your environments?

**Comment by wolfgang-ch** [comment] 2018-01-06 06:39
>  Can you also test in your environments?

I'll test it in the next days, currently I'm struggling with the newest version and the gadle updates because my last VTM update is 6 months ago

**Comment by devemux86** [comment] 2018-01-09 17:32
@wolfgang-ch did you have the chance to test the proposed flicker fix and on which platforms?

**Comment by wolfgang-ch** [comment] 2018-01-10 07:41
With the libGDX branch the flickering disappeared. I added some log statements to be shure that the correct code is used.

My platform is:
- Win 10 1709
- NVIDIA Quadro M1000M
  with "Buffer-flipping mode" reset to "Auto-select"

**Comment by devemux86** [comment] 2018-01-10 07:43
Thanks for the feedback!
That's great news, will probably merge the change in `master`.

@Longri can you test [libGDX](https://github.com/mapsforge/vtm/tree/libGDX) branch also on macOS?

**Comment by Longri** [comment] 2018-01-13 09:50
I can confirm that I have no flickering effect with some tests on MacOS with LibGdx !

**Comment by devemux86** [comment] 2018-01-13 12:26
Thank you all for your feedback!
Fixed in #149.

**Closed by devemux86** 2018-01-13 12:26 UTC
Labels: bug
