### ISSUE TITLE
Missing areas

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/vtm#984] opened 2022-11-26 19:11 UTC
Sometime areas are incomplete or totally missing.

Mapsforge:
![mapsforge](https://user-images.githubusercontent.com/5493128/204105258-43c3135d-1b45-4d58-87e5-699828c0ac9f.jpg)

VTM:
![vtm](https://user-images.githubusercontent.com/5493128/204105262-66aada22-eeda-4022-8644-595464da0fac.jpg)

**Comment by devemux86** [comment] 2022-11-26 19:28
To examine more easily the reports, can you mention for each example the:
- Map file
- Map style
- Coordinates

**Comment by Klaus-Tockloth** [comment] 2022-11-26 19:43
I will send you a download link (for map and theme) via mail. Screenshots are taken from Cruiser 3.0.2 and Cruiser GL 3.0.2. Coordinates are 51.95443 N and 7.51634 O.

**Comment by devemux86** [comment] 2022-11-26 19:44
This is a common OpenGL problem with overlapping areas of the same type get subtracted.
Especially with patterns, it was also discussed in https://github.com/mapsforge/vtm/issues/212.

---

Overlapping map files were fixed in https://github.com/mapsforge/vtm/pull/903 https://github.com/mapsforge/vtm/pull/905.

**Comment by Klaus-Tockloth** [comment] 2022-11-26 19:55
Map: https://download.freizeitkarte-osm.de/android/latest/freizeitkarte_nordrhein-westfalen.map.zip
Theme: [freizeitkarte-v5.zip](https://github.com/mapsforge/vtm/files/10096936/freizeitkarte-v5.zip)

**Comment by devemux86** [comment] 2023-01-23 11:09
I cannot reproduce the case with the building (latest map + theme).
In the image, it seems a rectangle overlaps the building?

But I can reproduce the case with the green pattern (with visible outlines).
What line is this rule in the map theme?

If there are >1 same patterns on top of each other,
then it's the issue with overlapping areas subtracted (https://github.com/mapsforge/vtm/issues/1010).

**Comment by devemux86** [comment] 2023-01-23 12:07
I cannot reproduce the case with the building (latest map + theme).
In the image, it seems a rectangle overlaps the building?

I can reproduce the case with the green pattern (with visible outlines).
@Klaus-Tockloth what line is this rule in the map theme?

If there are >1 same patterns on top of each other,
then it's the issue with overlapping areas subtracted (https://github.com/mapsforge/vtm/issues/1010).

**Comment by devemux86** [comment] 2023-01-24 09:18
Let's merge it in https://github.com/mapsforge/vtm/issues/1010.

**Closed by devemux86** 2023-01-24 09:18 UTC
