### ISSUE TITLE
Mapzen partial grid is displayed

### ISSUE THREAD

**Issue by wolfgang-ch** [mapsforge/vtm#356] opened 2017-06-04 13:58 UTC
In the left screen the grid is hidden but still partially displayed.

These maps are using the own tile server and not the OpenSciMap as it may look like because of the upper right button, this button is just for testing (and is not yet working :-)

![vtm-grid-2](https://cloud.githubusercontent.com/assets/1283445/26762199/752eef92-493e-11e7-98f2-67d8f68bda3b.png)

**Comment by devemux86** [comment] 2017-06-04 14:17
Is it a Mapsforge map or online vector tiles?

Mapsforge maps with area stroke or semi-transparent fill can have [tile grid artifacts](https://groups.google.com/forum/#%21topic/mapsforge-dev/GadiGI5iQNU).
That can be [solved](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#known-pitfalls) with slightly different map creation options.

**Comment by devemux86** [comment] 2017-06-04 15:02
_(Please answer in new posts, as edits don't notify anyone)_

If use vector tiles, does default implementation has grid lines, e.g. [MapTest](https://github.com/mapsforge/vtm/blob/master/vtm-playground/src/org/oscim/test/MapTest.java)?
Also make sure to not add a tile grid below map layers.

**Comment by wolfgang-ch** [comment] 2017-06-05 07:06
Im using the VtmThemes.MAPZEN theme with my own tile server. 

The gridlines on the left screenshot are also displayed when just only the base map is displayed without any additional layers.

To display the gridlines, I'm using the handy feature by pressing the [G key ](https://github.com/mapsforge/vtm/blob/master/vtm-gdx/src/org/oscim/gdx/InputHandler.java#L139)

**Comment by devemux86** [comment] 2017-06-05 07:22
Well now we have more info. :slightly_smiling_face: 
So you're using Mapzen tiles from your own server and the Mapzen theme.

If you don't add a tile grid in any way then those appear to be rendering artifacts at tile seams.

e.g. MapboxTest does not show any of those (zoom 16):
![mapzen](https://cloud.githubusercontent.com/assets/3484020/26774378/ac680cd8-49d8-11e7-97cd-18dea66546f4.png)

**Comment by devemux86** [comment] 2017-06-05 07:28
Please provide some coordinates of the area and can check a simple map implementation without grid layer to be sure.

**Comment by wolfgang-ch** [comment] 2017-06-05 09:14
I updated the [VTM RCP app](https://github.com/wolfgang-ch/vtm-with-rcp/blob/master/VTM_RCP_App/src/vtm/rcp/app/GdxMapApp.java#L150) to use an own tile server, 

I also increased MAX_TILT = 88 in Viewport.java, it would be easier when this value could be set with an API :-)

Map position for the screenshot

lat:47.18467635070152, 
lon:8.76715664951468

X:0.5243532129153186, Y:0.3509727327464605, Z:15

![vtm-grid](https://cloud.githubusercontent.com/assets/1283445/26777801/d6781ac6-49de-11e7-9d31-d16cd8b8b929.png)

**Comment by devemux86** [comment] 2017-06-05 09:23
> I also increased MAX_TILT = 88 in Viewport.java, it would be easier when this value could be set with an API :-)

You can use the various `Viewport` setters, e.g. `map.viewport().setMaxTilt()`

**Comment by devemux86** [comment] 2017-06-05 09:34
It doesn't appear something strange in MapboxTest with official Mapzen tiles.
If you use them how does it look?

![mapzen](https://cloud.githubusercontent.com/assets/3484020/26778722/2592942c-49eb-11e7-8802-dd03f37b6fad.png)

**Comment by wolfgang-ch** [comment] 2017-06-05 12:05
I think in your screenshot you are just a bit too far, if you zoom closer then the grid shoud appear.

I created a new screenshot at this location

lat:47.17568389059868, 
lon:8.772514329443709

X:0.5243680953595659, Y:0.35100948313170116, Z:16


![mapboxtest](https://cloud.githubusercontent.com/assets/1283445/26783329/dc045ed2-49f7-11e7-9ddd-88b38c2cd6aa.png)

**Comment by devemux86** [comment] 2017-06-05 12:17
At above coordinates / zoom there are no grid lines with MapboxTest:
(with official Mapzen map and VTM implementation and Mapzen theme)

![mapzen](https://cloud.githubusercontent.com/assets/3484020/26783645/ed8cf100-4a01-11e7-9f50-e2521560c1c1.png)

**Comment by wolfgang-ch** [comment] 2017-06-05 12:31
This is strange, I've not changed the Mapzen theme and running also the MapboxTest app. 
Interesting is that the green lines are not displayed in your map.

**Comment by devemux86** [comment] 2017-06-05 12:36
Do you perform the MapboxTest with your tiles or Mapzen's ones?
If they're custom ones, probably need debugging there?

**Comment by wolfgang-ch** [comment] 2017-06-05 12:39
I'm using this tile source with my API key

```        
UrlTileSource tileSource = MapboxTileSource.builder()
                .apiKey("mapzen-xxxxxxx") // Put a proper API key
                .httpFactory(new OkHttpEngine.OkHttpFactory())
                //.locale("en")
                .build();
```

**Comment by devemux86** [comment] 2017-09-20 19:14
Closing as cannot reproduce, please reopen if needed.

**Closed by devemux86** 2017-09-20 19:14 UTC
Labels: question

**Comment by wolfgang-ch** [comment] 2017-09-21 05:11
It seems that the map data are somehow solved, the green parts are now total different painted

![vtm-partial-grid](https://user-images.githubusercontent.com/1283445/30679717-aa81a312-9e9b-11e7-8f9a-ff79d8819c10.png)
