### ISSUE TITLE
cleanup mBaseLayer in Map

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#137] opened 2016-08-16 21:32 UTC
mBaseLayer in Map.java does not really serve any purpose anymore.
Now that all layers are themed, who cares if one defined the mBaseLayer?
It is never used besides for applying a theme and there it's not needed either, is it?

**Comment by devemux86** [comment] 2016-08-17 06:08
Duplicate of #102.

**Closed by devemux86** 2016-08-17 06:08 UTC
