### ISSUE TITLE
Renderer broken (highways oneway)

### ISSUE THREAD

**Issue by ago75** [mapsforge/vtm#410] opened 2017-09-27 07:48 UTC
started with thank you for the wonderful work you are carrying on.
I would point out an anomaly that I found with the package downloaded last night, hoping to do something useful:

lineSymbol src = "assets: symbols / oneway.svg" 
zoomLevel: 16
mapsforge map

the render is all black es. highways.

thank you

**Comment by devemux86** [comment] 2017-09-27 08:02
Oneways were rendered differently via line stipples, which didn't worked correctly in some GPU (#363), leading to what you describe (see screenshot there).
Now with the line symbols (#124), have not seen that situation again.

Please provide more information if the problem persists, like a screenshot and graphics card model.
Also can try using POT textures and see what happens:
```java
Parameters.POT_TEXTURES = true;
```

**Comment by devemux86** [comment] 2017-09-27 08:07
Closing as duplicate of #363, please provide any information or reopen there.

**Closed by devemux86** 2017-09-27 08:07 UTC
Labels: duplicate
