### ISSUE TITLE
Render themes: stroke-width and other elements not scaled

### ISSUE THREAD

**Issue by stleusc** [mapsforge/vtm#130] opened 2016-08-14 23:20 UTC
using my Galaxy S7 areas defined as below show no outline. On old, lowres devices it shows.

```xml
<area fill="#FFB2A9" stroke="#aa94a4" stroke-width="0.2"/>
```

Reason is that these dimensions (and others) are not scaled based on device resolution.

below is official mapsforge code which takes care of scaling
```java
} else if (STROKE_WIDTH.equals(name)) {
      this.strokeWidth = XmlUtils.parseNonNegativeFloat(name, value) * displayModel.getScaleFactor();
```

**Comment by devemux86** [comment] 2016-08-15 08:03
We need more work on that area, also keeping in mind the OpenGL differences with software rendering.

Closing as duplicate of #67.

**Closed by devemux86** 2016-08-15 08:03 UTC
Labels: enhancement
