### ISSUE TITLE
Circle map style

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/vtm#122] opened 2016-08-12 08:00 UTC
Tried to apply <circle> to a node in styles with no effect. Applying <symbol> to the same node draws the icon, so the rule is correct.

**Comment by devemux86** [comment] 2016-08-12 08:36
- In [VectorTileLoader](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/VectorTileLoader.java#L332) the relevant theme hook is not called
- And in [LabelTileLoaderHook](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/layers/tile/vector/labeling/LabelTileLoaderHook.java#L50) the `CircleStyle` rendering is not implemented

**Comment by andreynovikov** [comment] 2016-08-12 08:44
Sorry, I'm a dumb in OpenGL. Would be happy to implement it but can not.

**Comment by andreynovikov** [comment] 2016-10-11 13:12
@devemux86 I have tried to implement it but it does not work. Here is what I have done:
https://github.com/andreynovikov/vtm/commit/b90250d0e1a6e5a8c8a38443281c25bc2a18dd79
`CircleBucket.Renderer.draw(...)` is called but nothing is rendered. I've even tried to set `gl_FragColor` to constant vec4 to make it fill everything with one color but it didn't happen too.

Previously I succeeded to draw a circle in my custom layer renderer:
https://github.com/andreynovikov/maptrek/blob/master/app/src/main/java/mobi/maptrek/layers/marker/MarkerRenderer.java#L303
but now, due to my zero knowledge in OpenGL and 3D graphics, I can not understand where I am wrong. Can you please take a look?

**Comment by andreynovikov** [comment] 2016-10-11 13:17
In particular I am not sure about this:
https://github.com/andreynovikov/vtm/commit/b90250d0e1a6e5a8c8a38443281c25bc2a18dd79#diff-3ef0e84115b68031311480bc4df9053bR57
this:
https://github.com/andreynovikov/vtm/commit/b90250d0e1a6e5a8c8a38443281c25bc2a18dd79#diff-3ae74d34e3a6fc0e023696264bb5a3c2R88
and all circle.glsl:
https://github.com/andreynovikov/vtm/commit/b90250d0e1a6e5a8c8a38443281c25bc2a18dd79#diff-bc033069a629d2d0dad4030d1654f5c4R1

**Comment by devemux86** [comment] 2016-10-11 15:33
I'll need to debug it to see what happens.
Probably create a PR to see it in action in a branch?

**Comment by Klaus-Tockloth** [comment] 2016-10-29 18:39
Circles are an important feature in my freizeitkarte theme. I use it e.g. for rendering bollards:

```
      <m e="node" k="*" v="bollard" zoom-min="17">
        <circle radius="0.15" scale-radius="true" fill="#4c4c4c" />
      </m>
```

It would be great if someone could look into this.

**Comment by andreynovikov** [comment] 2016-11-14 08:12
@devemux86 did you have a chance to look at my buggy code? :) I've tried to use SVGs instead of circles for the time being but the problem is that SVGs are treated as symbols and are not tilted together with map. So I need true vector circles.

**Comment by devemux86** [comment] 2016-11-14 08:22
@andreynovikov sorry not had time to check it yet..
BTW have you included integration with theme API too?

>the problem is that SVGs are treated as symbols and are not tilted together with map

What do you mean, that they're like billboards?

**Comment by andreynovikov** [comment] 2016-11-14 08:35
What is theme API integration?

Yes, with that rule:
```
<m v="tree" zoom-min="16">
   <symbol src="assets:symbols/tree.svg" />
</m>
```

**Comment by devemux86** [comment] 2016-11-14 08:38
>What is theme API integration?

I mean can we test the new circle code in a render theme rule?

**Comment by andreynovikov** [comment] 2016-11-14 09:08
Ah, yes. :)

**Comment by devemux86** [comment] 2016-12-04 19:53
@andreynovikov I merged PR #202 in [issue_202](https://github.com/mapsforge/vtm/tree/issue_202) branch with additional [improvements](https://github.com/mapsforge/vtm/commit/cf4d4cccd879d89e8efcb3f746540934d502c967) to enable the rendering and a sample for easy testing.

There are two ways to implement circles in OpenGL (@hjanetzek any hint?):
- Via point primitives, we'd probably need GLSL `#version 120` (not best for compatibility)
- Via regular quads and clip the circle with the fragment shader

For now I implemented the 2nd method, not finished yet - they're just squares. :slightly_smiling_face: 
So need more work, plus the elements size isn't completely stable during zoom..

**Comment by devemux86** [comment] 2016-12-04 20:09
Forgot to mention that with the point method the max point size is controlled by the graphics hardware.
Also with default implementation the circles are like billboards.

**Comment by devemux86** [comment] 2016-12-06 19:26
I implemented OpenGL circles via point primitives, since it was a much quicker process.
We still have some things to check:
- Circles are like billboards
- Include more style options, e.g. stroke, scale radius

Additionally we can examine further if it's more convenient to include circles via quads.
I'll probably push the initial implementation in another branch for anyone wanting to play.

**Comment by devemux86** [comment] 2016-12-06 19:28
Running the `CircleTest` you can see current rendering:

![circles](https://cloud.githubusercontent.com/assets/3484020/20940304/ea1c957e-bbfa-11e6-8e3e-66f70da7b0f8.png)

**Comment by andreynovikov** [comment] 2016-12-07 19:58
I have taken circle shader from location indicator and it tilts perfectly. I've used it in my another custom map layer and it works there too. But bucket renderers are slightly different from map layer renderers so I do not understand where's the problem.

**Comment by devemux86** [comment] 2016-12-07 20:15
Location renderer uses a simple quad, those by default are tilted and enlarged.
Another major difference it has as input only 1 location, so can easily translate the view to draw it.

In the case of several circles in a bucket, we have many locations simultaneously.
It's straightforward for drawing the quads as regular rectangles, then we need to clip them to circles in fragment shader (per location).

All these are more easy with point primitives (current implementation), though they have their own peculiarities.

I'm not sure yet which method is better for our needs (if both work as intended).
I'd like to try again the quads path, probably activate them too with some style option.

**Comment by devemux86** [comment] 2016-12-08 12:37
I added separate shaders for circles via quads or points, controlled via `GLAdapter.CIRCLE_QUADS`.
That will allow us to advance any solution independently as we wish.

**Comment by Klaus-Tockloth** [comment] 2016-12-08 16:48
On the example picture the circles are looking very unsharp. Why is that so?

**Comment by devemux86** [comment] 2016-12-08 16:54
The [above](https://github.com/mapsforge/vtm/issues/122#issuecomment-265247602) screenshot is with GL points. In them I have not put yet antialiased edges because we'd need extra OpenGL extension and wanted to think a bit more about it. So in the meantime I have enabled just a smooth color fade, from center to edges.

**Comment by devemux86** [comment] 2016-12-08 16:56
See also another screenshot in forum [announcement](https://groups.google.com/forum/#!topic/mapsforge-dev/A6b8ntGPVXA).

**Comment by devemux86** [comment] 2016-12-12 08:17
Closing in favor of #268 for GL points and #269 for GL quads.

**Closed by devemux86** 2016-12-12 08:17 UTC
Labels: enhancement
