### ISSUE TITLE
White Bar on Map at Zoom-Level 8 using Mapsforge Maps

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#347] opened 2017-04-30 22:43 UTC
Something I saw with the [Kurviger App](https://play.google.com/store/apps/details?id=gr.talent.kurviger.pro), which uses VTM and Mapsforge offline maps, is that at zoom-level 8 a white bar appears, when having the Baden-Württemberg map loaded, see attached screenshot.

![offline_map_white_bar](https://cloud.githubusercontent.com/assets/1553525/25568622/143ad4b2-2e4a-11e7-9fd3-df9fa3b49bb7.png)

**Comment by devemux86** [comment] 2017-05-01 09:30
I can confirm that.
Several Mapsforge maps at zoom level 8 can render with white stripes near edges.

**Comment by devemux86** [comment] 2018-04-14 12:30
Closing as duplicate of older #264.

**Closed by devemux86** 2018-04-14 12:30 UTC
Labels: duplicate

**Comment by devemux86** [comment] 2018-04-15 08:56
Fixed via #526.
